### PR TITLE
Added a tab and ui element for junk locations

### PR DESCRIPTION
**Pull request by matthewkirby**
Allows you to select locations to generate a seed with the junkLocations option. The ui element sits on its own tab, fills 50% of the width (something else could go on this tab and the tab can be renamed, just didnt need the space). The new ui element is designed to take a list of locations and a setting name. It can then be used as a ui element for that setting (for now junk locations, but could trivially also be used for disabledLocations etc). 
image

It features a full list on the left and list of enabled locations on the right. You can click any number of locations on either side to select them and then click the add or remove buttons to move items that are selected on the appropriate side to the other. The reset button resets the setting back to an empty list. 

The text input bar at the bottom is a filter, type in parts of a check and it will filter both sides of the above display (filtering does not change the setting, just what is displayed). Adding and removing locations while the filter is active works properly and does not have an effect on items that are filtered out at the time. The red X in the corner appears when you type in the filter and allows for an easy reset of the filter.

The input bar and red is styled to be flexible to adding another inline component. I want to enable a dropdown menu of all possible flags. These flags are not yet implemented so adding this feature right now does not make sense. It will be as simple as building the list of flags from the list of locations, throwing them into a dropdown menu, and using it as an additional filtering parameter.

### CODE REVIEW

**Comment by matthewkirby** [comment]
I also chose to build this component in a directory as it had a bunch of files (other components and styles) that were only relevant for itself and I did not want to clutter the directory. If there is anything you'd like changed, definitely let me know and I can take care of it!

**Comment by Nax** [comment]
You have a conflict on `Generator.jsx` to solve.
Also, does this properly work with stable? (hide the tab + don't interfere with seed generation)

**Comment by matthewkirby** [comment]
I resolved the conflict but I am having difficulty testing it with stable. There is absolutely no way it will work right now. But I can't seem to get the link to update to core stable so it might take me a bit to get that tested and resolved. I am also not sure what the best practice is for doing this.

```jsx
import { SETTINGS_CATEGORIES, DEFAULT_SETTINGS, itemPool as makeItemPool, locationList as makeLocationList } from '@ootmm/core';
```

This line will fail in `Generator.jsx`. I can probably put the last bit in a try/catch which then could disable the rest but that is ugly. Granted, if this is a temporary thing that could be removed when stable is updated it could be fine for now.

**Comment by matthewkirby** [comment]
It was painstaking haha (mainly because i swapped computers) but I added some checks to ensure that the gui works for both the develop and master branches of core. These checks should probably be removed when this feature is merged to master in core but it works now. It does throw warning when you first render the app about the hook not being found. I assume that these will only appear over the app (vs in the developer console) in dev mode and they will be suppressed in the release.

**Comment by Nax** [comment]
Nice job 👍

**Pull request merged**
